# We like Ruby 1.8 hash syntax for dynamic key support
HashSyntax:
  Enabled: false

# While we like guard clauses, nested conditionals are okay sometimes
GuardClause:
  Enabled: false

# `raise` and `fail` are both fine
SignalException:
  Enabled: false

# Compact class/module nesting is fine
ClassAndModuleChildren:
  Enabled: false