language: ruby
bundler_args: --without debug
script: "bundle exec rspec"
cache: false 
rvm:
  - 2.1.3
  - 2.1.6
  - 2.2.3
  - 2.3.0
sudo: false
env: CI=yes
before_install: 'gem install bundler -v "~> 1.12"'
